"use server";

import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

type Module = "videos" | "notes" | "notices";

async function requireAdmin() { const session = await auth(); if (session?.user.role !== "admin" || !session.user.id || !session.user.email) throw new Error("Unauthorized"); return { id: session.user.id, email: session.user.email }; }
function value(formData: FormData, key: string) { return String(formData.get(key) || "").trim(); }
function url(value: string, optional = false) { if (!value && optional) return null; try { const parsed = new URL(value); if (parsed.protocol !== "http:" && parsed.protocol !== "https:") throw new Error(); return parsed.toString(); } catch { throw new Error("Enter a valid http(s) URL."); } }
async function enabledCourse(courseId: string, module: Module) { const course = await prisma.course.findUnique({ where: { id: courseId }, select: { id: true, name: true, hasVideos: true, hasNotes: true, hasNotices: true } }); const enabled = module === "videos" ? course?.hasVideos : module === "notes" ? course?.hasNotes : course?.hasNotices; if (!course || !enabled) throw new Error(`Choose a course with ${module} enabled.`); return course; }
async function log(admin: { id: string; email: string }, action: "CONTENT_CREATE" | "CONTENT_UPDATE" | "CONTENT_DELETE", title: string, courseName: string) { await prisma.activityLog.create({ data: { adminId: admin.id, adminEmail: admin.email, action, studentId: null, studentName: title, studentEmail: courseName } }); }
function refresh(module: Module) { revalidatePath(`/admin/${module}`); revalidatePath("/admin/activity"); revalidatePath("/course"); }
function done(module: Module, courseId: string, state: string) { refresh(module); redirect(`/admin/${module}?course=${encodeURIComponent(courseId)}&${state}=1`); }

export async function createVideoTopic(formData: FormData) { const admin = await requireAdmin(); const courseId = value(formData, "courseId"); const name = value(formData, "name"); try { if (!name) throw new Error("Enter a topic name."); const course = await enabledCourse(courseId, "videos"); const order = await prisma.videoTopic.count({ where: { courseId } }); const topic = await prisma.videoTopic.create({ data: { courseId, name, order } }); await log(admin, "CONTENT_CREATE", `Video topic: ${topic.name}`, course.name); done("videos", courseId, "created"); } catch (error) { redirect(`/admin/videos?course=${encodeURIComponent(courseId)}&error=${encodeURIComponent(error instanceof Error ? error.message : "Unable to create topic.")}`); } }
export async function updateVideoTopic(id: string, formData: FormData) { const admin = await requireAdmin(); const name = value(formData, "name"); const topic = await prisma.videoTopic.findUnique({ where: { id }, include: { course: true } }); if (!topic) redirect("/admin/videos?error=Topic+not+found."); try { if (!name) throw new Error("Enter a topic name."); await enabledCourse(topic!.courseId, "videos"); const updated = await prisma.videoTopic.update({ where: { id }, data: { name } }); await log(admin, "CONTENT_UPDATE", `Video topic: ${updated.name}`, topic!.course.name); done("videos", topic!.courseId, "updated"); } catch (error) { redirect(`/admin/videos?course=${topic!.courseId}&error=${encodeURIComponent(error instanceof Error ? error.message : "Unable to update topic.")}`); } }
export async function deleteVideoTopic(id: string) { const admin = await requireAdmin(); const topic = await prisma.videoTopic.findUnique({ where: { id }, include: { course: true } }); if (!topic) redirect("/admin/videos"); await prisma.$transaction(async (tx) => { await tx.videoTopic.delete({ where: { id } }); const remaining = await tx.videoTopic.findMany({ where: { courseId: topic.courseId }, orderBy: { order: "asc" } }); for (const [order, item] of remaining.entries()) await tx.videoTopic.update({ where: { id: item.id }, data: { order } }); }); await log(admin, "CONTENT_DELETE", `Video topic: ${topic.name}`, topic.course.name); done("videos", topic.courseId, "deleted"); }
export async function moveVideoTopic(id: string, direction: "up" | "down") { const topic = await prisma.videoTopic.findUnique({ where: { id } }); if (!topic) redirect("/admin/videos"); const swap = await prisma.videoTopic.findFirst({ where: { courseId: topic!.courseId, order: topic!.order + (direction === "up" ? -1 : 1) } }); if (swap) await prisma.$transaction([prisma.videoTopic.update({ where: { id }, data: { order: -1 } }), prisma.videoTopic.update({ where: { id: swap.id }, data: { order: topic!.order } }), prisma.videoTopic.update({ where: { id }, data: { order: swap.order } })]); done("videos", topic!.courseId, "updated"); }
export async function createVideo(formData: FormData) { const admin = await requireAdmin(); const topicId = value(formData, "topicId"); const title = value(formData, "title"); try { const topic = await prisma.videoTopic.findUnique({ where: { id: topicId }, include: { course: true } }); if (!topic || !title) throw new Error("Enter a video title."); await enabledCourse(topic.courseId, "videos"); const video = await prisma.video.create({ data: { videoTopicId: topicId, title, url: url(value(formData, "url"))!, order: await prisma.video.count({ where: { videoTopicId: topicId } }) } }); await log(admin, "CONTENT_CREATE", `Video: ${video.title}`, topic.course.name); done("videos", topic.courseId, "created"); } catch (error) { redirect(`/admin/videos?error=${encodeURIComponent(error instanceof Error ? error.message : "Unable to add video.")}`); } }
export async function updateVideo(id: string, formData: FormData) { const admin = await requireAdmin(); const video = await prisma.video.findUnique({ where: { id }, include: { videoTopic: { include: { course: true } } } }); if (!video) redirect("/admin/videos"); try { const title = value(formData, "title"); if (!title) throw new Error("Enter a video title."); await enabledCourse(video!.videoTopic.courseId, "videos"); const updated = await prisma.video.update({ where: { id }, data: { title, url: url(value(formData, "url"))! } }); await log(admin, "CONTENT_UPDATE", `Video: ${updated.title}`, video!.videoTopic.course.name); done("videos", video!.videoTopic.courseId, "updated"); } catch (error) { redirect(`/admin/videos?course=${video!.videoTopic.courseId}&error=${encodeURIComponent(error instanceof Error ? error.message : "Unable to update video.")}`); } }
export async function deleteVideo(id: string) { const admin = await requireAdmin(); const video = await prisma.video.findUnique({ where: { id }, include: { videoTopic: { include: { course: true } } } }); if (!video) redirect("/admin/videos"); await prisma.$transaction(async (tx) => { await tx.video.delete({ where: { id } }); const remaining = await tx.video.findMany({ where: { videoTopicId: video!.videoTopicId }, orderBy: { order: "asc" } }); for (const [order, item] of remaining.entries()) await tx.video.update({ where: { id: item.id }, data: { order } }); }); await log(admin, "CONTENT_DELETE", `Video: ${video!.title}`, video!.videoTopic.course.name); done("videos", video!.videoTopic.courseId, "deleted"); }
export async function moveVideo(id: string, direction: "up" | "down") { const video = await prisma.video.findUnique({ where: { id }, include: { videoTopic: true } }); if (!video) redirect("/admin/videos"); const swap = await prisma.video.findFirst({ where: { videoTopicId: video!.videoTopicId, order: video!.order + (direction === "up" ? -1 : 1) } }); if (swap) await prisma.$transaction([prisma.video.update({ where: { id }, data: { order: -1 } }), prisma.video.update({ where: { id: swap.id }, data: { order: video!.order } }), prisma.video.update({ where: { id }, data: { order: swap.order } })]); done("videos", video!.videoTopic.courseId, "updated"); }

export async function createNote(formData: FormData) { const admin = await requireAdmin(); const courseId = value(formData, "courseId"); const title = value(formData, "title"); try { if (!title) throw new Error("Enter a note title."); const course = await enabledCourse(courseId, "notes"); const note = await prisma.noteLink.create({ data: { courseId, title, url: url(value(formData, "url"))!, order: await prisma.noteLink.count({ where: { courseId } }) } }); await log(admin, "CONTENT_CREATE", `Note: ${note.title}`, course.name); done("notes", courseId, "created"); } catch (error) { redirect(`/admin/notes?course=${encodeURIComponent(courseId)}&error=${encodeURIComponent(error instanceof Error ? error.message : "Unable to add note.")}`); } }
export async function updateNote(id: string, formData: FormData) { const admin = await requireAdmin(); const note = await prisma.noteLink.findUnique({ where: { id }, include: { course: true } }); if (!note) redirect("/admin/notes"); try { const title = value(formData, "title"); if (!title) throw new Error("Enter a note title."); await enabledCourse(note!.courseId, "notes"); const updated = await prisma.noteLink.update({ where: { id }, data: { title, url: url(value(formData, "url"))! } }); await log(admin, "CONTENT_UPDATE", `Note: ${updated.title}`, note!.course.name); done("notes", note!.courseId, "updated"); } catch (error) { redirect(`/admin/notes?course=${note!.courseId}&error=${encodeURIComponent(error instanceof Error ? error.message : "Unable to update note.")}`); } }
export async function deleteNote(id: string) { const admin = await requireAdmin(); const note = await prisma.noteLink.findUnique({ where: { id }, include: { course: true } }); if (!note) redirect("/admin/notes"); await prisma.$transaction(async (tx) => { await tx.noteLink.delete({ where: { id } }); const remaining = await tx.noteLink.findMany({ where: { courseId: note!.courseId }, orderBy: { order: "asc" } }); for (const [order, item] of remaining.entries()) await tx.noteLink.update({ where: { id: item.id }, data: { order } }); }); await log(admin, "CONTENT_DELETE", `Note: ${note!.title}`, note!.course.name); done("notes", note!.courseId, "deleted"); }
export async function moveNote(id: string, direction: "up" | "down") { const note = await prisma.noteLink.findUnique({ where: { id } }); if (!note) redirect("/admin/notes"); const swap = await prisma.noteLink.findFirst({ where: { courseId: note!.courseId, order: note!.order + (direction === "up" ? -1 : 1) } }); if (swap) await prisma.$transaction([prisma.noteLink.update({ where: { id }, data: { order: -1 } }), prisma.noteLink.update({ where: { id: swap.id }, data: { order: note!.order } }), prisma.noteLink.update({ where: { id }, data: { order: swap.order } })]); done("notes", note!.courseId, "updated"); }

export async function createNotice(formData: FormData) { const admin = await requireAdmin(); const courseId = value(formData, "courseId"); const title = value(formData, "title"); const body = value(formData, "body"); try { if (!title || !body) throw new Error("Enter a title and announcement text."); const course = await enabledCourse(courseId, "notices"); const notice = await prisma.notice.create({ data: { courseId, title, body, url: url(value(formData, "url"), true) } }); await log(admin, "CONTENT_CREATE", `Notice: ${notice.title}`, course.name); done("notices", courseId, "created"); } catch (error) { redirect(`/admin/notices?course=${encodeURIComponent(courseId)}&error=${encodeURIComponent(error instanceof Error ? error.message : "Unable to create notice.")}`); } }
export async function updateNotice(id: string, formData: FormData) { const admin = await requireAdmin(); const notice = await prisma.notice.findUnique({ where: { id }, include: { course: true } }); if (!notice) redirect("/admin/notices"); try { const title = value(formData, "title"); const body = value(formData, "body"); if (!title || !body) throw new Error("Enter a title and announcement text."); await enabledCourse(notice!.courseId, "notices"); const updated = await prisma.notice.update({ where: { id }, data: { title, body, url: url(value(formData, "url"), true) } }); await log(admin, "CONTENT_UPDATE", `Notice: ${updated.title}`, notice!.course.name); done("notices", notice!.courseId, "updated"); } catch (error) { redirect(`/admin/notices?course=${notice!.courseId}&error=${encodeURIComponent(error instanceof Error ? error.message : "Unable to update notice.")}`); } }
export async function deleteNotice(id: string) { const admin = await requireAdmin(); const notice = await prisma.notice.findUnique({ where: { id }, include: { course: true } }); if (!notice) redirect("/admin/notices"); await prisma.notice.delete({ where: { id } }); await log(admin, "CONTENT_DELETE", `Notice: ${notice!.title}`, notice!.course.name); done("notices", notice!.courseId, "deleted"); }
