"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

export type AttemptQuestion = { id: string; sectionName: string; text: string; options: string[]; optionOrder: number[] };

export function AttemptRunner({ attemptId, testName, questions, initialAnswers, initialFlags, initialRemainingSeconds }: { attemptId: string; testName: string; questions: AttemptQuestion[]; initialAnswers: Record<string, number>; initialFlags: string[]; initialRemainingSeconds: number | null }) {
  const [index, setIndex] = useState(0); const [answers, setAnswers] = useState(initialAnswers); const [flags, setFlags] = useState(initialFlags); const [remaining, setRemaining] = useState(initialRemainingSeconds); const [saving, setSaving] = useState(false); const router = useRouter(); const answersRef = useRef(answers); const flagsRef = useRef(flags); const remainingRef = useRef(remaining);
  useEffect(() => { answersRef.current = answers; }, [answers]); useEffect(() => { flagsRef.current = flags; }, [flags]); useEffect(() => { remainingRef.current = remaining; }, [remaining]);
  async function persist(extra: Record<string, unknown> = {}) { setSaving(true); try { const response = await fetch(`/api/attempts/${attemptId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answers: answersRef.current, flaggedQuestionIds: flagsRef.current, timeRemainingSeconds: remainingRef.current, ...extra }) }); if (!response.ok) throw new Error("Save failed"); } finally { setSaving(false); } }
  async function finish(auto = false) { const unanswered = questions.filter((question) => answersRef.current[question.id] === undefined).length; const flagged = flagsRef.current.length; if (!auto && !window.confirm(`Submit now? ${unanswered} unanswered and ${flagged} flagged question(s) will be submitted as they are.`)) return; await persist({ complete: true, timeRemainingSeconds: Math.max(0, remainingRef.current ?? 0) }); router.push("/course"); router.refresh(); }
  useEffect(() => { if (remaining === null) return; const timer = window.setInterval(() => { setRemaining((current) => { const next = Math.max(0, (current ?? 0) - 1); if (next === 0) { window.clearInterval(timer); void finish(true); } return next; }); }, 1000); return () => window.clearInterval(timer); }, []);
  const question = questions[index]; if (!question) return null;
  const selectAnswer = async (originalOptionIndex: number) => { const next = { ...answersRef.current, [question.id]: originalOptionIndex }; setAnswers(next); answersRef.current = next; await persist(); };
  const toggleFlag = async () => { const next = flagsRef.current.includes(question.id) ? flagsRef.current.filter((id) => id !== question.id) : [...flagsRef.current, question.id]; setFlags(next); flagsRef.current = next; await persist(); };
  const formatTime = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${(seconds % 60).toString().padStart(2, "0")}`;
  return <main className="course attempt-page"><p className="eyebrow">MOCK TEST · {testName}</p>{remaining !== null && <p className="timer">Time remaining: {formatTime(remaining)}</p>}<div className="attempt-layout"><aside className="question-nav"><strong>Questions</strong><div>{questions.map((item, itemIndex) => <button key={item.id} className={`${itemIndex === index ? "active" : ""} ${answers[item.id] !== undefined ? "answered" : ""} ${flags.includes(item.id) ? "flagged" : ""}`} onClick={() => setIndex(itemIndex)}>{itemIndex + 1}</button>)}</div><p className="fine">{saving ? "Saving…" : "Answers save automatically"}</p><button className="button" onClick={() => finish()}>Submit test</button></aside><section className="card question-screen"><p className="fine">{question.sectionName} · Question {index + 1} of {questions.length}</p><h1>{question.text}</h1><div className="answer-options">{question.optionOrder.map((originalIndex, optionIndex) => <label key={originalIndex} className={answers[question.id] === originalIndex ? "selected" : ""}><input type="radio" name="answer" checked={answers[question.id] === originalIndex} onChange={() => void selectAnswer(originalIndex)} /> <span>{String.fromCharCode(65 + optionIndex)}.</span> {question.options[originalIndex]}</label>)}</div><div className="attempt-controls"><button type="button" className={flags.includes(question.id) ? "secondary active-flag" : "secondary"} onClick={() => void toggleFlag()}>{flags.includes(question.id) ? "Remove flag" : "Flag for review"}</button><div><button type="button" className="secondary" disabled={index === 0} onClick={() => setIndex(index - 1)}>Previous</button><button type="button" disabled={index === questions.length - 1} onClick={() => setIndex(index + 1)}>Next</button></div></div></section></div></main>;
}
