"use client";

import { useState } from "react";
import { BookViewer } from "@/components/book-viewer";
import { AvailableTest, MockTestList } from "@/components/mock-test-list";
import { ProgressToggle } from "@/components/progress-toggle";
import { toggleLiveClassAttendance, toggleNoteSeen, toggleVideoSeen } from "@/app/course/actions";

type CourseTab = "book" | "mock-test" | "videos" | "notes" | "live-classes" | "notices";
type VideoTopic = { id: string; name: string; videos: { id: string; title: string; url: string; seen: boolean }[] };
type Note = { id: string; title: string; url: string; seen: boolean };
type LiveClass = { id: string; title: string; url: string; body: string | null; createdAt: Date; attended: boolean };
type Notice = { id: string; title: string; url: string | null; body: string; createdAt: Date };

export function CourseTabs({ hasBook, hasMockTest, hasVideos, hasNotes, hasLiveClasses, hasNotices, mockTests = [], videoTopics = [], notes = [], liveClasses = [], notices = [] }: { hasBook: boolean; hasMockTest: boolean; hasVideos: boolean; hasNotes: boolean; hasLiveClasses: boolean; hasNotices: boolean; mockTests?: AvailableTest[]; videoTopics?: VideoTopic[]; notes?: Note[]; liveClasses?: LiveClass[]; notices?: Notice[] }) {
  const tabs: { id: CourseTab; label: string }[] = [...(hasBook ? [{ id: "book" as const, label: "Book" }] : []), ...(hasMockTest ? [{ id: "mock-test" as const, label: "Mock Test" }] : []), ...(hasVideos ? [{ id: "videos" as const, label: "Videos" }] : []), ...(hasNotes ? [{ id: "notes" as const, label: "Notes" }] : []), ...(hasLiveClasses ? [{ id: "live-classes" as const, label: "Live Classes" }] : []), ...(hasNotices ? [{ id: "notices" as const, label: "Notices" }] : [])];
  const [activeTab, setActiveTab] = useState<CourseTab>(tabs[0]?.id || "book");
  const [bookOpen, setBookOpen] = useState(false);
  return <section className="course-tabs"><nav className="course-tab-nav" aria-label="Course sections">{tabs.map(tab => <button key={tab.id} type="button" className={activeTab === tab.id ? "active" : ""} onClick={() => { setActiveTab(tab.id); if (tab.id !== "book") setBookOpen(false); }} aria-selected={activeTab === tab.id} role="tab">{tab.label}</button>)}</nav>
    {hasBook && <div role="tabpanel" hidden={activeTab !== "book"}><section className="book-section"><div><span>01</span><h2>Book</h2><p>Read your study book in StepUp Academy.</p></div>{bookOpen ? <><button type="button" className="button small" style={{ marginBottom: 14 }} onClick={() => setBookOpen(false)}>← Close book</button><BookViewer /></> : <div className="book-launch"><p>Ready to study? Open your book whenever you are.</p><button type="button" className="button" onClick={() => setBookOpen(true)}>Open Book</button></div>}</section></div>}
    {hasMockTest && <div role="tabpanel" hidden={activeTab !== "mock-test"}><MockTestList tests={mockTests} /></div>}
    {hasVideos && <div role="tabpanel" hidden={activeTab !== "videos"}><section className="module-section"><h2>Video lessons</h2>{videoTopics.length ? videoTopics.map(topic => <details className="video-topic" key={topic.id} open><summary>{topic.name}</summary><ul>{topic.videos.map(video => <li className="progress-item" key={video.id}><ProgressToggle checked={video.seen} label="Watched" onToggle={() => toggleVideoSeen(video.id)} /><a href={video.url} target="_blank" rel="noreferrer">{video.title}</a></li>)}</ul>{!topic.videos.length && <p className="fine">No lessons in this topic yet.</p>}</details>) : <section className="empty"><h2>Video lessons coming soon</h2><p>Your instructor has not added any videos yet.</p></section>}</section></div>}
    {hasNotes && <div role="tabpanel" hidden={activeTab !== "notes"}><section className="module-section"><h2>Notes</h2>{notes.length ? <ul className="link-list">{notes.map(note => <li className="progress-item" key={note.id}><ProgressToggle checked={note.seen} label="Read" onToggle={() => toggleNoteSeen(note.id)} /><a href={note.url} target="_blank" rel="noreferrer">{note.title}</a></li>)}</ul> : <section className="empty"><h2>Notes coming soon</h2><p>Your instructor has not added any notes yet.</p></section>}</section></div>}
    {hasLiveClasses && <div role="tabpanel" hidden={activeTab !== "live-classes"}><section className="module-section"><h2>Live Classes</h2>{liveClasses.length ? <div className="notice-list">{liveClasses.map(liveClass => <article className="notice-card" key={liveClass.id}><time>{new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(liveClass.createdAt))}</time><h3>{liveClass.title}</h3>{liveClass.body && <p>{liveClass.body}</p>}<div className="content-actions"><ProgressToggle checked={liveClass.attended} label="Attended" onToggle={() => toggleLiveClassAttendance(liveClass.id)} /><a className="text-link" href={liveClass.url} target="_blank" rel="noreferrer">Join class →</a></div></article>)}</div> : <section className="empty"><h2>No live classes yet</h2><p>Upcoming classes will appear here.</p></section>}</section></div>}
    {hasNotices && <div role="tabpanel" hidden={activeTab !== "notices"}><section className="module-section"><h2>Notices</h2>{notices.length ? <div className="notice-list">{notices.map(notice => <article className="notice-card" key={notice.id}><time>{new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(notice.createdAt))}</time><h3>{notice.title}</h3><p>{notice.body}</p>{notice.url && <a className="text-link" href={notice.url} target="_blank" rel="noreferrer">Open link →</a>}</article>)}</div> : <section className="empty"><h2>No notices yet</h2><p>New announcements will appear here.</p></section>}</section></div>}
  </section>;
}
