"use client";
import { useState } from "react";
import { BookViewer } from "@/components/book-viewer";
import { AvailableTest, MockTestList } from "@/components/mock-test-list";
type CourseTab = "book" | "mock-test" | "videos" | "notes" | "notices";
type VideoTopic = { id: string; name: string; videos: { id: string; title: string; url: string }[] };
type Note = { id: string; title: string; url: string };
type Notice = { id: string; title: string; url: string | null; body: string; createdAt: Date };
export function CourseTabs({ hasBook, hasMockTest, hasVideos, hasNotes, hasNotices, mockTests = [], videoTopics = [], notes = [], notices = [] }: { hasBook: boolean; hasMockTest: boolean; hasVideos: boolean; hasNotes: boolean; hasNotices: boolean; mockTests?: AvailableTest[]; videoTopics?: VideoTopic[]; notes?: Note[]; notices?: Notice[] }) {
  const tabs: { id: CourseTab; label: string }[] = [...(hasBook ? [{ id: "book" as const, label: "Book" }] : []), ...(hasMockTest ? [{ id: "mock-test" as const, label: "Mock Test" }] : []), ...(hasVideos ? [{ id: "videos" as const, label: "Videos" }] : []), ...(hasNotes ? [{ id: "notes" as const, label: "Notes" }] : []), ...(hasNotices ? [{ id: "notices" as const, label: "Live classes & notices" }] : [])];
  const [activeTab, setActiveTab] = useState<CourseTab>(tabs[0]?.id || "book"); const [bookOpen, setBookOpen] = useState(false);
  return <section className="course-tabs"><nav className="course-tab-nav" aria-label="Course sections">{tabs.map(tab => <button key={tab.id} type="button" className={activeTab === tab.id ? "active" : ""} onClick={() => { setActiveTab(tab.id); if (tab.id !== "book") setBookOpen(false); }} aria-selected={activeTab === tab.id} role="tab">{tab.label}</button>)}</nav>{hasBook && <div role="tabpanel" hidden={activeTab !== "book"}><section className="book-section"><div><span>01</span><h2>Book</h2><p>Read your study book in StepUp Academy.</p></div>{bookOpen ? <><button type="button" className="button small" style={{ marginBottom: 14 }} onClick={() => setBookOpen(false)}>← Close book</button><BookViewer /></> : <div className="book-launch"><p>Ready to study? Open your book whenever you are.</p><button type="button" className="button" onClick={() => setBookOpen(true)}>Open Book</button></div>}</section></div>}{hasMockTest && <div role="tabpanel" hidden={activeTab !== "mock-test"}><MockTestList tests={mockTests} /></div>}{hasVideos && <div role="tabpanel" hidden={activeTab !== "videos"}><section className="module-section"><h2>Video lessons</h2>{videoTopics.length ? videoTopics.map(topic => <details className="video-topic" key={topic.id} open><summary>{topic.name}</summary><ul>{topic.videos.map(video => <li key={video.id}><a href={video.url} target="_blank" rel="noreferrer">{video.title}</a></li>)}</ul>{!topic.videos.length && <p className="fine">No lessons in this topic yet.</p>}</details>) : <section className="empty"><h2>Video lessons coming soon</h2><p>Your instructor has not added any videos yet.</p></section>}</section></div>}{hasNotes && <div role="tabpanel" hidden={activeTab !== "notes"}><section className="module-section"><h2>Notes</h2>{notes.length ? <ul className="link-list">{notes.map(note => <li key={note.id}><a href={note.url} target="_blank" rel="noreferrer">{note.title}</a></li>)}</ul> : <section className="empty"><h2>Notes coming soon</h2><p>Your instructor has not added any notes yet.</p></section>}</section></div>}{hasNotices && <div role="tabpanel" hidden={activeTab !== "notices"}><section className="module-section"><h2>Live classes &amp; notices</h2>{notices.length ? <div className="notice-list">{notices.map(notice => <article className="notice-card" key={notice.id}><time>{new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(notice.createdAt))}</time><h3>{notice.title}</h3><p>{notice.body}</p>{notice.url && <a className="text-link" href={notice.url} target="_blank" rel="noreferrer">Open link →</a>}</article>)}</div> : <section className="empty"><h2>No notices yet</h2><p>New class announcements will appear here.</p></section>}</section></div>}</section>;
}
