"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { bulkSetApproval, deleteStudent, setApproval, updateCourse } from "@/app/admin/actions";

export type StudentRow = { id: string; name: string; email: string; course: "AFTER_SEE" | "CLASS_11" | "CLASS_12"; status: "PENDING" | "APPROVED" | "DECLINED" | "SUSPENDED"; registeredAt: string };
const labels = { AFTER_SEE: "After SEE", CLASS_11: "Class 11", CLASS_12: "Class 12" };

export function StudentTable({ students, directory = false }: { students: StudentRow[]; directory?: boolean }) {
  const [selected, setSelected] = useState<string[]>([]); const [pending, startTransition] = useTransition(); const router = useRouter();
  const allSelected = students.length > 0 && students.every((student) => selected.includes(student.id));
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const toggleAll = () => setSelected(allSelected ? [] : students.map((student) => student.id));
  const bulk = (status: "APPROVED" | "DECLINED") => { if (!window.confirm(`${status === "APPROVED" ? "Approve" : "Decline"} ${selected.length} selected student(s)?`)) return; startTransition(async () => { await bulkSetApproval(selected, status); setSelected([]); router.refresh(); }); };
  const exportCsv = () => { const escape = (value: string) => `"${value.replaceAll('"', '""')}"`; const lines = [["Name", "Email", "Course", "Status", "Registration Date"], ...students.map((student) => [student.name, student.email, labels[student.course], student.status, student.registeredAt])].map((row) => row.map(escape).join(",")); const url = URL.createObjectURL(new Blob([lines.join("\r\n")], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "stepup-students.csv"; link.click(); URL.revokeObjectURL(url); };
  return <><div className="selection-bar"><label><input type="checkbox" checked={allSelected} onChange={toggleAll}/> Select all</label>{selected.length > 0 && <div><span>{selected.length} selected</span><button disabled={pending} onClick={() => bulk("APPROVED")}>Approve selected</button><button disabled={pending} className="decline" onClick={() => bulk("DECLINED")}>Decline selected</button></div>}{directory && <button className="export-button" onClick={exportCsv}>Export to CSV</button>}</div><div className="table directory">{students.length === 0 ? <section className="empty"><h2>No students found</h2></section> : students.map((student) => <article key={student.id}><label className="row-check"><input type="checkbox" checked={selected.includes(student.id)} onChange={() => toggle(student.id)} aria-label={`Select ${student.name}`}/></label><div><h2>{student.name} {directory && <span className={`status ${student.status.toLowerCase()}`}>{student.status}</span>}</h2><p>{student.email} · {directory ? `Registered ${student.registeredAt}` : `${labels[student.course]} · ${student.registeredAt}`}</p></div><div className="row">{directory ? <><form action={(formData) => startTransition(async () => { await updateCourse(student.id, formData); router.refresh(); })}><select name="course" defaultValue={student.course}>{Object.entries(labels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><button>Save course</button></form>{student.status === "PENDING" && <><button onClick={() => startTransition(async () => { await setApproval(student.id, "APPROVED"); router.refresh(); })}>Approve</button><button className="decline" onClick={() => startTransition(async () => { await setApproval(student.id, "DECLINED"); router.refresh(); })}>Decline</button></>}{student.status === "APPROVED" && <button className="decline" onClick={() => startTransition(async () => { await setApproval(student.id, "SUSPENDED"); router.refresh(); })}>Suspend</button>}{student.status === "SUSPENDED" && <button onClick={() => startTransition(async () => { await setApproval(student.id, "APPROVED"); router.refresh(); })}>Reinstate</button>}{student.status === "DECLINED" && <button onClick={() => startTransition(async () => { await setApproval(student.id, "APPROVED"); router.refresh(); })}>Approve</button>}<button className="delete" onClick={() => { if (window.confirm(`Delete ${student.name}'s account permanently? This cannot be undone.`)) startTransition(async () => { await deleteStudent(student.id); router.refresh(); }); }}>Delete</button></> : <><button onClick={() => startTransition(async () => { await setApproval(student.id, "APPROVED"); router.refresh(); })}>Approve</button><button className="decline" onClick={() => startTransition(async () => { await setApproval(student.id, "DECLINED"); router.refresh(); })}>Decline</button></>}</div></article>)}</div></>;
}
