import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { AdminNav } from "@/components/admin-nav";
import { MockTestEditor } from "@/components/mock-test-editor";
import { ConfirmDeleteMockTest } from "@/components/confirm-delete-mock-test";
import { deleteMockTest, updateMockTest } from "../actions";

export default async function EditMockTest({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; saved?: string }> }) { if ((await auth())?.user.role !== "admin") redirect("/admin/login"); const [{ id }, query] = await Promise.all([params, searchParams]); const [courses, test] = await Promise.all([prisma.course.findMany({ where: { hasMockTest: true }, select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.mockTest.findUnique({ where: { id }, include: { sections: { include: { questions: { orderBy: { order: "asc" } } }, orderBy: { order: "asc" } } } })]); if (!test) redirect("/admin/mock-tests"); const initial = { courseId: test.courseId, name: test.name, timeLimitMinutes: test.timeLimitMinutes, negativeMarkingPercent: test.negativeMarkingPercent, isPublished: test.isPublished, leaderboardHidden: test.leaderboardHidden, sections: test.sections.map((section) => ({ name: section.name, pointsPerQuestion: section.pointsPerQuestion, questions: section.questions.map((question) => ({ text: question.text, options: question.options, correctOptionIndex: question.correctOptionIndex })) })) }; return <main className="admin"><AdminNav /><header><p className="eyebrow">ASSESSMENTS</p><h1>Edit mock test</h1><p>Changes to published tests are allowed and saved immediately.</p></header>{query.error && <p className="error">{query.error}</p>}{query.saved && <p className="success">Mock test saved.</p>}<MockTestEditor courses={courses} initial={initial} action={updateMockTest.bind(null, test.id)} /><ConfirmDeleteMockTest action={deleteMockTest.bind(null, test.id)} /></main>; }
