ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'COURSE_CREATE';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'COURSE_UPDATE';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'COURSE_DELETE';
