import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { AdminNav } from "@/components/admin-nav";
import { createLiveClass, deleteLiveClass, updateLiveClass } from "@/app/admin/content/actions";

export default async function LiveClasses({ searchParams }: { searchParams: Promise<{ course?: string; error?: string; created?: string; updated?: string; deleted?: string }> }) {
  if ((await auth())?.user.role !== "admin") redirect("/admin/login");
  const [params, courses] = await Promise.all([searchParams, prisma.course.findMany({ where: { hasLiveClasses: true }, orderBy: { name: "asc" } })]);
  const courseId = courses.some((course) => course.id === params.course) ? params.course! : courses[0]?.id;
  const liveClasses = courseId ? await prisma.liveClass.findMany({ where: { courseId }, orderBy: { createdAt: "desc" } }) : [];
  return <main className="admin"><AdminNav /><header><p className="eyebrow">COURSE CONTENT</p><h1>Live classes</h1><p>Add Zoom or other meeting links separately from general notices.</p></header>{params.error && <p className="error">{params.error}</p>}{params.created && <p className="success">Live class created.</p>}{params.updated && <p className="success">Live class updated.</p>}{params.deleted && <p className="success">Live class deleted.</p>}{courses.length === 0 ? <section className="empty"><h2>No Live Classes courses</h2><p>Enable Live Classes in Manage Courses before adding sessions.</p></section> : <><form className="filters"><select name="course" defaultValue={courseId}>{courses.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select><button>View course</button></form><section className="card admin-card"><h2>Schedule live class</h2><form action={createLiveClass} className="form compact"><input type="hidden" name="courseId" value={courseId} /><input name="title" placeholder="Revision class" required /><input name="url" type="url" placeholder="https://zoom.us/..." required /><textarea name="body" placeholder="Optional description" /><button>Post live class</button></form></section><div className="content-list">{liveClasses.map((liveClass) => <section className="content-group" key={liveClass.id}><form action={updateLiveClass.bind(null, liveClass.id)} className="form compact"><input name="title" defaultValue={liveClass.title} required /><input name="url" type="url" defaultValue={liveClass.url} required /><textarea name="body" defaultValue={liveClass.body || ""} placeholder="Optional description" /><div className="row"><button className="secondary">Save</button><button formAction={deleteLiveClass.bind(null, liveClass.id)} className="delete">Delete</button></div></form></section>)}</div></>}</main>;
}
